name: 'Build and Deploy production'

on:
    push: 
        tags: 
            - '*'

jobs:
    release-docker-image-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              name: Check out code
          
            - name: Build & push Docker image Github
              uses: mr-smithers-excellent/docker-build-push@v6
              with:
                image: ${{ github.event.repository.name }}
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}